### PR TITLE
Java 10 compatibility

### PR DESCRIPTION
**Pull request by Trinova**
Fixes for compatibility with Java 10 including:
- upgraded dependency of `org.ow2.asm-asm`
- fixed test which was dependent on implementation specifics

### CODE REVIEW

**Comment by hendriks73** [comment]
I have tested this with Java8 and Java10 and it seems to work like a charm.
I would appreciate it, if the PR got merged.

Thanks!

**Comment by hendriks73** [comment]
Hey @osundblad ! Are you still maintaining this project?

**Comment by osundblad** [comment]
Sorry I really need to be more active here, I will try to make a release tonight.

**Comment by osundblad** [comment]
Ok, now the 0.6.8 release is on Maven Central now. I only did some minor testing (with Java 8) so please let me know if there are any issues.

PS I'll try to be more active, but my new job consumes most of my time right now.

**Comment by hendriks73** [comment]
That's the nasty thing about paid jobs—they cost way too much time.

Thanks for merging and releasing! Much appreciated.

**Comment by osundblad** [comment]
I will close this issue as fixed then.

PS Thanks again for the PR

**Pull request merged**
