### PR TITLE
0.6.9-SNAPSHOT should work with Java versions up to 11

### PR DESCRIPTION
**Pull request by osundblad**
Please try it out! I am not using Java 11 enough to know if this works, tested it on BBUtil and it seems to work.

### CODE REVIEW

**Comment by Trinova** [comment]
The test `ImplicitNotNullInstrumenterTest.innerClassWithoutConstructor_shouldWork()` doesn't pass if the default JDK is Java11. 
This is due to the changes made to nested classes in Java11 and the TestCompiler class using the system java compiler. It can be fixed by setting the `-source 1.8 -target 1.8` flags for the programatically used compiler, although this creates a warning when no JRE8 is provided to link against.
> warning: [options] bootstrap class path not set in conjunction with -source 8

Using `1.7` as source and target versions causes errors in the test suit
```java.lang.AssertionError: 
Expected: (an instance of java.lang.IllegalArgumentException and exception with message is "NotNull annotated argument 0 (parameter 's') of se/eris/test/TestNotNull$Sub.overload must not be null")
     but: exception with message is "NotNull annotated argument 0 (parameter 's') of se/eris/test/TestNotNull$Sub.overload must not be null" message was "NotNull annotated argument 0 of se/eris/test/TestNotNull$Sub.overload must not be null"
Stacktrace was: java.lang.IllegalArgumentException: NotNull annotated argument 0 of se/eris/test/TestNotNull$Sub.overload must not be null
	[...]
```
Since maven is configured to use `1.7` as source and target version but the tests fail if the TestCompiler uses it, both should be increased to `1.8` and if possible tied together to avoid them to diverge in the future.

The plugin itself seems to work so far but I didn't find the time to test it on a bigger project.

Small nitpicking: `TestNotNull.Inner` is not an _inner_ but a _static nested_ class. _inner_ refers to the _non-static_ nested class types (member, local or anonymous).

**Comment by osundblad** [comment]
@Trinova Hi and thanks for the comment/info. This seems a bit complex to solve today (Christmas eve). I tried your patch and it works for source/target 1.8 but not source/target 11. My gut feeling tells me this will require some work to solve.

About the small nitpick. I like those kinds of comments they improve the code. So I don't see it as nitpicking. It is valuable feedback and they are usually easy to fix too. To defend my mistake ASM before version 7 didn't differ between inner and nested classes (same callback) so we can pretend it was that which I intended to test ;-) I think that the java 11 problems might have something to to with that but I just saw it in the decompiled ASM library so I haven't had time to investigate yet.

**Comment by Trinova** [comment]
On the topic of Java11 and the synthetic constructors:
In Java a nested class has access to private members of it's host class and vice versa. The JVM specification did (does?) not allow such access. That's why the compiler created synthetic (since they had no counter part in the source) constructs with _package private_/_default_ visibility. This was a work around. 
Java11 introduced the concept of nests [JEP-181](https://openjdk.java.net/jeps/181) which makes these synthetic bridge methods and constructors obsolete, thus they are missing in the _.class_-files if compiled with a Java11 compiler.
The JLS does not make any comments about them because the way a compiler realizes the access to private members between host and nested class is an implementation detail of the compiler and could be different between different brands.

The byte code listings attached show how the Java11 version does just contain the generated default constructor (as the JLS demands) while the Java8 version gets a parameter of type `TestNotNull$1`. Why this happens is a miracle to me since `TestNotNull$1` does neither contain attributes nor methods.
A more comprehensible synthetic construct generated (in Java8) is `static String TestNotNull.Nested.access$100(TestNotNull.Nested)` which is used to expose the private attribute via a package private method. Compliant to this the call of `Nested.s` in `TestNotNull.createNested()` is changed to invoke `Nested.access$100()` instead of directly accessing `s`.

Bytecode listings:
TestNotNull$Nested.class: [TestNotNull$Nested.11.txt](https://github.com/osundblad/intellij-annotations-instrumenter-maven-plugin/files/2710600/TestNotNull.Nested.11.txt)
TestNotNull.class, TestNotNull$1.class, TestNotNull$Nested.class: [TestNotNull.8.txt](https://github.com/osundblad/intellij-annotations-instrumenter-maven-plugin/files/2710601/TestNotNull.8.txt)

I wonder if it is reasonable to inject checks in any synthetic constructs at all since they have no source code counterpart. I would currently favour to not modify them ever.

**Comment by osundblad** [comment]
You misunderstood me I don't want to check synthetic code that is why I have to identify it during implicit instrumentation. Synthetic parameters also mess up the parameter count since ASM visits the non synthetic parameters but the parameter name table I get (from ASM) includes the synthetic parameters.

And I would very much like pull requests to PRs. And if I don't answer questions here try to mail me directly (olle@eris.se) or even better the chat program Telegram (I will make a NotNull group as soon as anyone wants to join). If you rather just help me like you did now that is fine too (all feedback is good feedback).

**Comment by osundblad** [comment]
There should be a 0.6.9-RC1 on maven central by now.

**Comment by Trinova** [comment]
Since I don't know if this is intended: 
With the `TestSupportedJavaVersions` containing all versions from 7 to 11 the test suit can't pass if run with a JDK8. 

I think this is reasonable since I don't see any way to verify it's functionality for a Java version without the associated JDK. As long as the source and target bytecode levels configured stay `1.8` it'll work for that version upwards. If you want the plugin to be buildable with a JDK8 we need to invest some energy to run tests only up to the version of the executing JDK.

**Comment by Trinova** [comment]
> I know I thought it was worth the inconvenience to actually test all versions. But if you really want to use a lower JDK you can just edit the TestSupportedJavaVersions annotation and remove the versions above the JDK you have.

I second that. It's just a minor inconvenience. Most people will use the binaries from maven central anyway and have no interest in compiling the plugin them selves.

> Do you know a way not to duplicate the versions? As I understand it you can't use a field in the annotation and there is no "easy" way to access the values? Was thinking about using reflection to get them from the Annotation but decided to keep it simple (they are just a few lines apart now)

Sadly there is no way since it's an array. Values for annotations must be constant expressions and those are very limited in java [Constant Expression](https://docs.oracle.com/javase/specs/jls/se11/html/jls-15.html#jls-15.28). In short it's pretty much only literals of primitives and Strings or type names.
I think simple beats convenient here. If the test code becomes as complex as it's target it is not useful.

I wont be home before the 29th but I'll try to finish a merge request before the new year.

**Comment by osundblad** [comment]
A 0.6.9-RC2 is out on Maven central with Fixes for Enum with parameters and Inner class methods

**Comment by Trinova** [comment]
I just came up with another test scenario which I'll try to provide.
```@FunctionalInterface
interface Foo {
    public static void main(String... args){
        Foo foo = ()->{};
        foo.annotatedDefaultMethod(null);
    }
    default void annotatedDefaultMethod(@NotNull String notNull){
        //noop
    }
    void someMethod();
}
```
So in general I think once you merge the `java11` branch into master a `1.0` is justifiable.

**Pull request merged**
